# version: "3.8"
services:
  mtc_adapter:
    container_name: mtc_adapter
    hostname: mtc_adapter
    image: hemsaw/smartsaw-adapter:latest
    user: adapter
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    volumes:
      - "/etc/adapter/config/:/adapter/config/"
      - "/etc/adapter/data/:/adapter/data/"
      - "/etc/adapter/log/:/adapter/log/"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - 7878:7878/tcp
    working_dir: "/adapter"
    restart: unless-stopped

  mtc_agent:
    container_name: mtc_agent
    hostname: mtc_agent
    image: hemsaw/mtconnect:latest
    user: agent
    entrypoint: "/usr/bin/mtcagent run /mtconnect/config/agent.cfg"
    working_dir: "/home/agent"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    volumes:
      - "/etc/mtconnect/config/:/mtconnect/config/"
      - "/etc/mtconnect/data/ruby/:/mtconnect/data/ruby/"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - 5000:5000/tcp
    restart: unless-stopped
    depends_on:
      - mosquitto
      - mtc_adapter

  mosquitto:
    container_name: mosquitto
    hostname: mosquitto
    image: hemsaw/mosquitto:latest
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    volumes:
      - "/etc/mqtt/config/mosquitto.conf:/mosquitto/config/mosquitto.conf"
      - "/etc/mqtt/data/acl:/mosquitto/data/acl"
      - "/etc/mqtt/certs:/mosquitto/certs"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - 1883:1883/tcp
      - 9001:9001/tcp
    restart: unless-stopped

  ods:
    container_name: ods
    hostname: ods
    image: hemsaw/ods:latest
    user: ods
    working_dir: "/ods"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    volumes:
      - "/etc/ods/config/:/ods/"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - 9625:9625/tcp
    restart: unless-stopped
    depends_on:
      - mongodb

  devctl:
    container_name: devctl
    hostname: devctl
    image: hemsaw/devctl:latest
    user: devctl
    working_dir: "/devctl"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    volumes:
      - "/etc/devctl/config:/devctl/config"
      - "/etc/devctl/logs:/devctl/logs"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped
    depends_on:
      - mongodb
      - mosquitto

  mongodb:
    container_name: mongodb
    hostname: mongodb
    image: mongo:4.4
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    volumes:
      - "/etc/mongodb/data/db:/data/db"
      - "/etc/mongodb/config/:/etc/mongo/"
    command: ["mongod", "--config", "/etc/mongo/mongod.conf"]
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - 127.0.0.1:27017:27017/tcp
    restart: unless-stopped

  watchtower:
    container_name: watchtower
    hostname: watchtower
    image: containrrr/watchtower
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/timezone:/etc/timezone:ro
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_REMOVE_VOLUMES=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_ROLLING_RESTART=true
