version: '3.5'
services:
  mtc_agent:
    container_name: mtc_agent
    hostname: mtc_agent
    image: mtconnect/agent:latest
    user: agent
    ports: 
      - 5000:5000/tcp
    entrypoint: "/usr/bin/mtcagent run /mtconnect/config/agent.cfg"
    working_dir: "/home/agent"
    restart: unless-stopped
    volumes:
      - '/etc/mtconnect/agent/agent.cfg:/mtconnect/config/agent.cfg'
      - '/etc/mtconnect/devices/:/mtconnect/config/devices'
      - '/etc/mtconnect/ruby/:/mtconnect/config/ruby'
      - '/etc/mtconnect/styles/:/mtconnect/data/styles'

  mosquitto:
    container_name: mosquitto
    hostname: mosquitto
    image: eclipse-mosquitto:latest
    volumes:
      - "/etc/mosquitto/conf.d/mosquitto.conf:/mosquitto/config/mosquitto.conf"
      - "/etc/mosquitto/passwd:/mosquitto/data/passwd"
      - "/etc/mosquitto/acl:/mosquitto/data/acl"
    ports:
      - 1883:1883/tcp
      - 9001:9001/tcp
    restart: unless-stopped

  watchtower:
    container_name: watchtower
    hostname: watchtower
    image: containrrr/watchtower
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/timezone:/etc/timezone:ro
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_ROLLING_RESTART=true

  # restarter:
  #   container_name: restarter
  #   hostname: restarter
  #   image: docker:cli
  #   volumes: ["/var/run/docker.sock:/var/run/docker.sock"]
  #   command: ["/bin/sh", "-c", "while true; do sleep 86400; docker restart mtc_agent; done"]
  #   restart: unless-stopped