version: '3.5'
services:
  agent:
    container_name: mtc_agent
    hostname: mtc_agent
    image: hemsaw/mtconnect:latest
    user: agent
    environment:
      - TZ=Etc/UTC
      - DEBIAN_FRONTEND=noninteractive
    ports: 
      - 5000:5000/tcp
    entrypoint: "/usr/bin/mtcagent run /etc/mtconnect/data/dockerAgent.cfg"
    working_dir: "/etc/mtconnect/"
    restart: unless-stopped
    volumes:
      - '/etc/mtconnect/agent/dockerAgent.cfg:/etc/mtconnect/data/dockerAgent.cfg'
      - '/etc/mtconnect/devices/:/etc/mtconnect/data/devices'
      - '/etc/mtconnect/ruby/:/etc/mtconnect/data/ruby'

  mosquitto:
    container_name: mosquitto
    hostname: mosquitto
    image: eclipse-mosquitto:latest
    volumes:
      - "/etc/mosquitto/conf.d/mosquitto.conf:/mosquitto/config/mosquitto.conf"
      - "/etc/mosquitto/passwd:/mosquitto/data/passwd"
      - "/etc/mosquitto/acl:/mosquitto/data/acl"
    ports:
      - 1883:1883/tcp
    restart: unless-stopped

  watchtower:
    container_name: watchtower
    hostname: watchtower
    image: containrrr/watchtower
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/timezone:/etc/timezone:ro
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_ROLLING_RESTART=true